spring.application.name=SpringAI

# =========================
# CHAT MODEL - GROQ
# =========================

spring.ai.model.chat=openai

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-20b


# =========================
# EMBEDDING MODEL - OLLAMA
# =========================

spring.ai.model.embedding=ollama

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text


# =========================
# DISABLE OLLAMA CHAT
# =========================

spring.ai.ollama.chat.enabled=false