spring.application.name=SpringAI

# =========================
# CHAT MODEL - GROQ
# =========================

spring.ai.model.chat=openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=qwen/qwen3.6-27b
spring.ai.openai.chat.max-completion-tokens=500
spring.ai.openai.chat.reasoning-effort=none


# =========================
# EMBEDDING MODEL - OLLAMA
# =========================

spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text


# =========================
# DISABLE OLLAMA CHAT
# =========================

spring.ai.ollama.chat.enabled=false


# =========================
# POSTGRESQL
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/springai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update


# =========================
# PGVECTOR
# =========================

spring.ai.vectorstore.pgvector.initialize-schema=true